version: "3.9"

services: 
  app:
    image: "mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm"
    container_name: garage_app
    command: "tail -f /dev/null"
    environment:
      - HOME=/home/vscode
    env_file:
      - ../.env
    volumes:
      - ..:/workspace
    networks:
        - garage-3-network

  mssql: 
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "DevelopmentDB"
      MSSQL_SA_PASSWORD: "N&DevelopmentPassword"
    networks:
      - garage-3-network

networks:
  garage-3-network:
    driver: bridge
